extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_Rock2_rgba16[];
extern u8 ccm_dl_W1_ci8[];
extern u8 ccm_dl_W1_pal_rgba16[];
extern u8 ccm_dl_Material4_ci4[];
extern u8 ccm_dl_Material4_pal_rgba16[];
extern u8 ccm_dl_W2_ia16[];
extern u8 ccm_dl_GrassGreenEdge_ia16[];
extern u8 ccm_dl_Material7_ia16[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_0[76];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_main_mesh_layer_1_vtx_0[220];
extern Gfx ccm_dl_main_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_main_mesh_layer_1_vtx_1[115];
extern Gfx ccm_dl_main_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_main_mesh_layer_1_vtx_2[77];
extern Gfx ccm_dl_main_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_main_mesh_layer_1_vtx_3[64];
extern Gfx ccm_dl_main_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_main_mesh_layer_5_vtx_0[76];
extern Gfx ccm_dl_main_mesh_layer_5_tri_0[];
extern Gfx mat_ccm_dl_f3dlite_material[];
extern Gfx mat_revert_ccm_dl_f3dlite_material[];
extern Gfx mat_ccm_dl_f3dlite_material_002[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_002[];
extern Gfx mat_ccm_dl_f3dlite_material_003[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_003[];
extern Gfx mat_ccm_dl_f3dlite_material_005[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_005[];
extern Gfx mat_ccm_dl_f3dlite_material_006[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_006[];
extern Gfx mat_ccm_dl_f3dlite_material_007[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_007[];
extern Gfx ccm_dl_Circle_mesh_layer_1[];
extern Gfx ccm_dl_main_mesh_layer_1[];
extern Gfx ccm_dl_main_mesh_layer_5[];
