extern const GeoLayout Switchblock_Border_Red_MOP_geo[];
extern u8 Switchblock_Border_Red_MOP_Switchblock_MOP_0x5f1db0_rgba16_i8[];
extern Vtx Switchblock_Border_Red_MOP_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx Switchblock_Border_Red_MOP_Cube_001_mesh_layer_1_vtx_0[179];
extern Gfx Switchblock_Border_Red_MOP_Cube_001_mesh_layer_1_tri_0[];
extern Gfx mat_Switchblock_Border_Red_MOP_f3dlite_material_002[];
extern Gfx mat_revert_Switchblock_Border_Red_MOP_f3dlite_material_002[];
extern Gfx Switchblock_Border_Red_MOP_Cube_001_mesh_layer_1[];
