extern const GeoLayout barrel_geo[];
extern Lights1 barrel_Material__50_f3d_lights;
extern Lights1 barrel_Material__49_f3d_lights;
extern u8 barrel__5736BA6B_c_rgba16[];
extern u8 barrel__1CF5C9C9_c_rgba16[];
extern Vtx barrel_Bone_mesh_layer_1_vtx_0[21];
extern Gfx barrel_Bone_mesh_layer_1_tri_0[];
extern Vtx barrel_Bone_mesh_layer_1_vtx_1[10];
extern Gfx barrel_Bone_mesh_layer_1_tri_1[];
extern Gfx mat_barrel_Material__50_f3d[];
extern Gfx mat_barrel_Material__49_f3d[];
extern Gfx barrel_Bone_mesh_layer_1[];
