extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern Lights1 hmc_dl_f3dlite_material_003_lights;
extern Lights1 hmc_dl_mt_tree_palm_f3d_lights;
extern u8 hmc_dl_sand_rgba16[];
extern u8 hmc_dl_segment2_11C58_rgba16_ia16[];
extern u8 hmc_dl_mt_tree_palm_rgba16[];
extern Vtx hmc_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Cube_mesh_layer_1_vtx_0[19];
extern Gfx hmc_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Cube_002_mesh_layer_1_vtx_0[19];
extern Gfx hmc_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_0[25];
extern Gfx hmc_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_TREP_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_TREP_mesh_layer_1_vtx_0[298];
extern Gfx hmc_dl_TREP_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_TREP_001_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_TREP_001_mesh_layer_1_vtx_0[298];
extern Gfx hmc_dl_TREP_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_TREP_002_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_TREP_002_mesh_layer_1_vtx_0[298];
extern Gfx hmc_dl_TREP_002_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_dl_f3dlite_material_003[];
extern Gfx mat_hmc_dl_waer[];
extern Gfx mat_revert_hmc_dl_waer[];
extern Gfx mat_hmc_dl_mt_tree_palm_f3d[];
extern Gfx hmc_dl_Cube_mesh_layer_1[];
extern Gfx hmc_dl_Cube_002_mesh_layer_1[];
extern Gfx hmc_dl_Plane_mesh_layer_1[];
extern Gfx hmc_dl_TREP_mesh_layer_1[];
extern Gfx hmc_dl_TREP_001_mesh_layer_1[];
extern Gfx hmc_dl_TREP_002_mesh_layer_1[];
