extern const GeoLayout peashooter_geo[];
extern Lights1 peashooter_body_002_f3d_lights;
extern Lights1 peashooter_eyes_002_f3d_lights;
extern u8 peashooter_body_ia4[];
extern u8 peashooter_eye_ia4[];
extern Vtx peashooter_Bone_mesh_layer_1_vtx_0[543];
extern Gfx peashooter_Bone_mesh_layer_1_tri_0[];
extern Vtx peashooter_Bone_mesh_layer_4_vtx_0[8];
extern Gfx peashooter_Bone_mesh_layer_4_tri_0[];
extern Gfx mat_peashooter_body_002_f3d[];
extern Gfx mat_peashooter_eyes_002_f3d[];
extern Gfx mat_revert_peashooter_eyes_002_f3d[];
extern Gfx peashooter_Bone_mesh_layer_1[];
extern Gfx peashooter_Bone_mesh_layer_4[];
