extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_f3dlite_material_001_lights;
extern Lights1 jrb_dl_f3dlite_material_lights;
extern u8 jrb_dl_ccm_textures_08800_rgba16_rgba16[];
extern u8 jrb_dl_ccm_textures_06000_rgba16_rgba16[];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_0[13544];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_1[3002];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx jrb_dl_Cube_mesh_layer_1[];
