extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_f3dlite_material_003_lights;
extern Lights1 jrb_dl_f3dlite_material_004_lights;
extern Lights1 jrb_dl_f3dlite_material_lights;
extern u8 jrb_dl_TexturSMG__299__ci8[];
extern u8 jrb_dl_TexturSMG__299__pal_rgba16[];
extern u8 jrb_dl_Mmc_kusaFUTI1___Copy_ci8[];
extern u8 jrb_dl_Mmc_kusaFUTI1___Copy_pal_rgba16[];
extern u8 jrb_dl_tempImgEd0099_ia16[];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_0[99];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_1[83];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx jrb_dl_Cube_mesh_layer_5_vtx_0[16];
extern Gfx jrb_dl_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_jrb_dl_f3dlite_material_003[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_003[];
extern Gfx mat_jrb_dl_f3dlite_material_004[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_004[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx jrb_dl_Cube_mesh_layer_1[];
extern Gfx jrb_dl_Cube_mesh_layer_5[];
