extern const GeoLayout Switchblock_Switch_Red_MOP_geo[];
extern u8 Switchblock_Switch_Red_MOP_Switchblock_Switch_MOP_rgba16_i8[];
extern Vtx Switchblock_Switch_Red_MOP_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx Switchblock_Switch_Red_MOP_Plane_mesh_layer_1_vtx_0[46];
extern Gfx Switchblock_Switch_Red_MOP_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_Switchblock_Switch_Red_MOP_f3dlite_material[];
extern Gfx mat_revert_Switchblock_Switch_Red_MOP_f3dlite_material[];
extern Gfx Switchblock_Switch_Red_MOP_Plane_mesh_layer_1[];
