extern const GeoLayout star_geo[];
extern Lights1 star_f3dlite_material_lights;
extern Lights1 star_f3dlite_material_001_lights;
extern u8 star_star_eye_rgba16_ia8[];
extern Vtx star_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx star_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx star_001_displaylist_mesh_layer_4_vtx_0[8];
extern Gfx star_001_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_star_f3dlite_material[];
extern Gfx mat_star_f3dlite_material_001[];
extern Gfx mat_revert_star_f3dlite_material_001[];
extern Gfx star_000_displaylist_mesh_layer_1[];
extern Gfx star_001_displaylist_mesh_layer_4[];
